//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("C2H4")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2.2.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2.2a+58de5f75d2b7d25e3f65454d78dba050ed62ae95")]
[assembly: System.Reflection.AssemblyProductAttribute("Big Pan Map Editor")]
[assembly: System.Reflection.AssemblyTitleAttribute("Big Pan Map Editor")]
[assembly: System.Reflection.AssemblyVersionAttribute("2.2.0.0")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows7.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows7.0")]

// MSBuild WriteCodeFragment クラスによって生成されました。

